package beads

import (
	"context"
	"fmt"
	"regexp"
	"time"
)

// Delta computes an incremental refresh of prev: the watermark is the max
// non-tombstone UpdatedAt in prev, capped to the current time so a
// future-dated tombstone can never push it past live edits. With no
// watermark (prev empty, or every issue in it tombstoned) Delta behaves like
// a full skeleton read. Otherwise it takes one snapshot, fetches every issue
// (including tombstones) with updated_at >= the watermark, and merges the
// result into prev: tombstoned ids are dropped, everything else is upserted
// by id. Concurrent callers are single-flighted via refreshMu, same as
// Export.
func (c *doltClient) Delta(ctx context.Context, prev []FullIssue) ([]FullIssue, error) {
	c.refreshMu.Lock()
	defer c.refreshMu.Unlock()

	snap, err := c.r.snapshot(ctx)
	if err != nil {
		return nil, err
	}
	asof := asOf(snap)

	wm := capToNow(maxUpdatedAt(prev))
	if wm == "" {
		return c.skeletonWhere(ctx, asof, false, "")
	}
	doltWM, err := wmToDolt(wm)
	if err != nil {
		// Defensive: an unparsable watermark falls back to a full read
		// rather than risking a broken SQL comparison.
		return c.skeletonWhere(ctx, asof, false, "")
	}
	lit, err := dateTimeLiteral(doltWM)
	if err != nil {
		return nil, err
	}
	changed, err := c.skeletonWhere(ctx, asof, true, "updated_at >= "+lit)
	if err != nil {
		return nil, err
	}
	return mergeDelta(prev, changed), nil
}

// capToNow clamps wm to the current time so a future-dated tombstone can't
// push the watermark past live edits; both are RFC3339 UTC, so plain string
// comparison matches chronological order.
func capToNow(wm string) string {
	if now := time.Now().UTC().Format(time.RFC3339); wm > now {
		return now
	}
	return wm
}

// maxUpdatedAt returns the maximum UpdatedAt among issues' non-tombstone
// entries, or "" if there are none. UpdatedAt is normalized RFC3339, which
// sorts lexicographically, so plain string comparison gives chronological
// order.
func maxUpdatedAt(issues []FullIssue) string {
	max := ""
	for _, iss := range issues {
		if iss.Status != "tombstone" && iss.UpdatedAt > max {
			max = iss.UpdatedAt
		}
	}
	return max
}

// wmToDolt converts an RFC3339 watermark (as stored in FullIssue.UpdatedAt)
// back to dolt's "2006-01-02 15:04:05" space form for the SQL comparison.
func wmToDolt(wm string) (string, error) {
	t, err := time.Parse(time.RFC3339, wm)
	if err != nil {
		return "", fmt.Errorf("parse watermark %q: %w", wm, err)
	}
	return t.UTC().Format("2006-01-02 15:04:05"), nil
}

// doltDateTimeLiteralPattern matches exactly the "2006-01-02 15:04:05" space
// form wmToDolt produces. The shared sqlLiteral (dolt_exec.go) deliberately
// rejects spaces in its charset to reject injection via arbitrary strings;
// this value is machine-generated by time.Format, never arbitrary input, so
// it gets its own tight validation instead of widening that shared,
// security-sensitive charset.
var doltDateTimeLiteralPattern = regexp.MustCompile(`^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$`)

// dateTimeLiteral quotes a dolt space-form datetime (from wmToDolt) as a SQL
// literal after verifying it matches that exact machine-generated shape.
func dateTimeLiteral(doltWM string) (string, error) {
	if !doltDateTimeLiteralPattern.MatchString(doltWM) {
		return "", fmt.Errorf("invalid dolt datetime literal %q", doltWM)
	}
	return "'" + doltWM + "'", nil
}

// mergeDelta applies changed onto prev (upsert by id; a tombstoned id is
// dropped instead), deduping by id, and returns the merged full set.
func mergeDelta(prev, changed []FullIssue) []FullIssue {
	merged := make(map[string]FullIssue, len(prev)+len(changed))
	for _, iss := range prev {
		merged[iss.ID] = iss
	}
	for _, iss := range changed {
		if iss.Status == "tombstone" {
			delete(merged, iss.ID)
			continue
		}
		merged[iss.ID] = iss
	}
	out := make([]FullIssue, 0, len(merged))
	for _, iss := range merged {
		out = append(out, iss)
	}
	return out
}

// attachCommentFingerprints stamps each issue in byID with a
// CommentFingerprint computed from a single aggregate query -- COUNT(*) and
// MAX(created_at) grouped by issue_id -- rather than a per-issue correlated
// subquery, so a skeleton read pays exactly one extra round trip through the
// serialized doltRunner regardless of how many issues it returns (ab-6irx.6).
//
// An issue with zero comments never appears in the GROUP BY result, so its
// CommentFingerprint is left at the Go zero value (""); only issues that
// have at least one comment get a non-empty fingerprint. That asymmetry is
// intentional, not a bug: it means "0 comments" and "never computed" look
// identical (""), which is exactly the safe default when comparing an old
// and new fingerprint -- both empty reads as "no change", never a spurious
// invalidation.
//
// Unmatched issue_ids (a comment on an issue outside the current byID set,
// e.g. a tombstoned issue excluded from this skeleton read) are silently
// skipped, mirroring attachLabels/attachDeps.
func (c *doltClient) attachCommentFingerprints(ctx context.Context, asof string, byID map[string]*FullIssue) error {
	q := "SELECT issue_id, COUNT(*) AS n, COALESCE(MAX(created_at),'') AS maxc FROM comments" + asof + " GROUP BY issue_id"
	rows, err := c.r.query(ctx, q)
	if err != nil {
		return err
	}
	for _, row := range rows {
		iss, ok := byID[str(row["issue_id"])]
		if !ok {
			continue
		}
		iss.CommentFingerprint = fmt.Sprintf("%d|%s", intOf(row["n"]), normalizeDoltTime(str(row["maxc"])))
	}
	return nil
}
